services:
  backend:
    build: backend
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_DB=web2_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/web2_db
    networks:
      - spring-postgres

  postgres:
    image: 'postgres:latest'
    container_name: web2_db
    environment:
      - POSTGRES_DB=web2_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - spring-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgressql/data
    
volumes:
  postgres_data:
networks:
  spring-postgres:
