<<<<<<< HEAD
<<<<<<< HEAD
services:
  backend:
    container_name: backend
    build: backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_APPLICATION_NAME=backend
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/web2_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - API_SECURITY_TOKEN_SECRET=my-secret-key
    networks:
      - spring-postgres
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    container_name: web2_db
    environment:
      - POSTGRES_DB=web2_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - spring-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data:
networks:
services:
  backend:
    container_name: backend
    build: backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_APPLICATION_NAME=backend
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/web2_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - API_SECURITY_TOKEN_SECRET=my-secret-key
    networks:
      - spring-postgres
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    container_name: web2_db
    environment:
      - POSTGRES_DB=web2_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - spring-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data:
networks:
>>>>>>> origin/feat-crud-processo-seletivo
  spring-postgres: