package com.rb.web2.domain.enums;

public enum Permissao {
    LOGIN_USER, // 1
    LOGOUT_USER, // 2
    REGISTER_USER, // 3
    EDIT_USER, // 4
    VIEW_USER, // 5
    EDIT_PROCESSO_SELETIVO, // 6
    VIEW_PROCESSO_SELETIVO, // 7
    VIEW_CRITERIOS, // 8
    EDIT_CRITERIOS, // 9
    EDIT_INSCRICAO, // 10
    VIEW_INSCRICAO, // 11
    EDIT_INSCRICOES, // 12
    VIEW_INSCRICOES, // 13
    VIEW_RESULTADOS, // 14
    EDIT_RESULTADOS, // 15
    EDIT_RESULTADO, // 16
    VIEW_RESULTADO, // 17
    EDIT_MEMBRO_COMISSAO, // 18
    VIEW_MEMBRO_COMISSAO, // 19
    VIEW_AGENDA, // 20
    EDIT_AGENDA, // 21
    VIEW_DOCUMENTO, // 22
    EDIT_DOCUMENTO, // 23
    VIEW_DOCUMENTOS, // 24
    EDIT_DOCUMENTOS, // 25
    HOMOLOGAR_DOCUMENTO_INSCRICAO, // 26
    VIEW_CARGOS, // 27
    EDIT_CARGOS, // 28
    VIEW_INSTITUICAO, // 29
    EDIT_INSTITUICAO, // 30
    VIEW_PONTUACOES, // 31
    EDIT_PONTUACOES, // 32
    VIEW_VAGAS, // 33
    EDIT_VAGAS, // 34
    VIEW_ETAPAS, // 35
    EDIT_ETAPAS, // 36
}
