package com.rb.web2.domain.enums;

public enum Permissao {
    LOGIN_USER, // 1
    LOGOUT_USER, // 2
    REGISTER_USER, // 3
    EDIT_USER, // 4
    VIEW_USER, // 5
    EDIT_USERS, // 6
    VIEW_USERS, // 7
    EDIT_PROCESSO_SELETIVO, // 8
    VIEW_PROCESSO_SELETIVO, // 9
    VIEW_CRITERIOS, // 10
    EDIT_CRITERIOS, // 11
    EDIT_INSCRICAO, // 12
    VIEW_INSCRICAO, // 13
    EDIT_INSCRICOES, // 14
    VIEW_INSCRICOES, // 15
    VIEW_RESULTADOS, // 16
    EDIT_RESULTADOS, // 17
    EDIT_RESULTADO, // 18
    VIEW_RESULTADO, // 19
    EDIT_MEMBRO_COMISSAO, // 20
    VIEW_MEMBRO_COMISSAO, // 21
    VIEW_AGENDA, // 22
    EDIT_AGENDA, // 23
    VIEW_DOCUMENTO, // 24
    EDIT_DOCUMENTO, // 25
    VIEW_DOCUMENTOS, // 26
    EDIT_DOCUMENTOS, // 27
    HOMOLOGAR_DOCUMENTO_INSCRICAO, // 28
    VIEW_CARGOS, // 29
    EDIT_CARGOS, // 30
    VIEW_INSTITUICAO, // 31
    EDIT_INSTITUICAO, // 32
    VIEW_PONTUACOES, // 33
    EDIT_PONTUACOES, // 34
    VIEW_VAGAS, // 35
    EDIT_VAGAS, // 36
    VIEW_ETAPAS, // 37
    EDIT_ETAPAS, // 38
}
